pull_request_rules:
  - name: Add needs-dco label when DCO check failed
    conditions:
      - base=main
      - -status-success=DCO
    actions:
      label:
        remove:
          - dco-passed
        add:
          - needs-dco
      comment:
        message: |
          @{{author}} Thanks for your contribution. Please submit with DCO, see the contributing guide https://github.com/milvus-io/milvus/blob/master/CONTRIBUTING.md#developer-certificate-of-origin-dco.
  - name: Add dco-passed label when DCO check passed
    conditions:
      - base=main
      - status-success=DCO
    actions:
      label:
        remove:
          - needs-dco
        add:
          - dco-passed

  - name: Add ci-passed when eligible
    conditions:
      - base=main
      - or:
        - and:
          - "status-success=UT on Ubuntu-22.04"
          - "status-success=Compile on macOS 15"
        - and:
          - -files~=^[^\.]+$
          - -files~=\.(?!md|png)
        - and:
          - -files~=^(?!\.github\/mergify\.yml).*$
    actions:
      label:
        add:
          - ci-passed

  - name: Remove ci-passed when CI failed
    conditions:
      - base=main
      - label=ci-passed
      - or:
        - "-status-success=UT on Ubuntu-22.04"
        - "-status-success=Compile on macOS 15"
      - files~=^(?!\.github\/mergify\.yml).*$
      - files~=\.(?!md|png)
    actions:
      label:
        remove:
          - ci-passed
