[package]
name = "milvus-sdk-rust"
description = "The official Milvus Rust SDK"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"

[lib]
name = "milvus"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = { version = "0.13.1", features = ["tls-native-roots", "prost"] }
prost = ">=0.13, <0.14"
tokio = { version = "1.17.0", features = ["full"] }
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
strum = "0.24"
strum_macros = "0.24"
base64 = "0.22.1"
dashmap = "5.5.3"
futures = "0.3.31"
lazy_static = "1.4"

[build-dependencies]
tonic-build = { version = "0.13", default-features = false, features = [
    "prost",
] }
protoc-bin-vendored = "=3.2.0"

[dev-dependencies]
rand = "0.8.5"

[[test]]
name = "alias"
path = "tests/v1/alias.rs"

[[test]]
name = "client"
path = "tests/v1/client.rs"

[[test]]
name = "collection"
path = "tests/v1/collection.rs"

[[test]]
name = "database"
path = "tests/v1/database.rs"

[[test]]
name = "index"
path = "tests/v1/index.rs"

[[test]]
name = "iterator"
path = "tests/v1/iterator.rs"

[[test]]
name = "milvus26"
path = "tests/v1/milvus26.rs"

[[test]]
name = "partition"
path = "tests/v1/partition.rs"

[[test]]
name = "query"
path = "tests/v1/query.rs"

[[test]]
name = "rbac"
path = "tests/v1/rbac.rs"

[[test]]
name = "resource_group"
path = "tests/v1/resource_group.rs"

[[test]]
name = "utility"
path = "tests/v1/utility.rs"

[[test]]
name = "client_keepalive"
path = "tests/v1/testsoutsideoftestsuite/client_keepalive.rs"

[[test]]
name = "client_with_timeout"
path = "tests/v1/testsoutsideoftestsuite/client_with_timeout.rs"

[[test]]
name = "client_search"
path = "tests/v1/testsoutsideoftestsuite/client_search.rs"

[[test]]
name = "collection_list_collections"
path = "tests/v1/testsoutsideoftestsuite/collection_list_collections.rs"

[[test]]
name = "collection_get_collection_stats"
path = "tests/v1/testsoutsideoftestsuite/collection_get_collection_stats.rs"

[[test]]
name = "collection_release_collection"
path = "tests/v1/testsoutsideoftestsuite/collection_release_collection.rs"

[[test]]
name = "mutate_delete"
path = "tests/v1/testsoutsideoftestsuite/mutate_delete.rs"

[[test]]
name = "cdc"
path = "tests/v1/cdc.rs"

[[test]]
name = "aggressive_hpc_testing"
path = "tests/v1/aggressivehpctesting/mod.rs"

[[example]]
name = "authentication"
path = "examples/v1/authentication.rs"

[[example]]
name = "cdc"
path = "examples/v1/cdc.rs"

[[example]]
name = "collection"
path = "examples/v1/collection.rs"

[[example]]
name = "database"
path = "examples/v1/database.rs"

[[example]]
name = "full_text_match"
path = "examples/v1/full_text_match.rs"

[[example]]
name = "index_example"
path = "examples/v1/index_example.rs"

[[example]]
name = "int8_vector"
path = "examples/v1/int8_vector.rs"

[[example]]
name = "iterator"
path = "examples/v1/iterator.rs"

[[example]]
name = "query_search"
path = "examples/v1/query_search.rs"

[[example]]
name = "resource_groups"
path = "examples/v1/resource_groups.rs"

[[example]]
name = "timestampz"
path = "examples/v1/timestampz.rs"

[[example]]
name = "upsert"
path = "examples/v1/upsert.rs"
