// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Status {
    #[deprecated]
    #[prost(enumeration = "ErrorCode", tag = "1")]
    pub error_code: i32,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub code: i32,
    #[prost(bool, tag = "4")]
    pub retriable: bool,
    #[prost(string, tag = "5")]
    pub detail: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "6")]
    pub extra_info:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KeyValuePair {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KeyDataPair {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Blob {
    #[prost(bytes = "vec", tag = "1")]
    pub value: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlaceholderValue {
    #[prost(string, tag = "1")]
    pub tag: ::prost::alloc::string::String,
    #[prost(enumeration = "PlaceholderType", tag = "2")]
    pub r#type: i32,
    /// values is a 2d-array of nq rows, every row contains a query vector.
    /// for dense vector, all rows are of the same length; for sparse vector,
    /// the length of each row may vary depending on their number of non-zeros.
    #[prost(bytes = "vec", repeated, tag = "3")]
    pub values: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlaceholderGroup {
    #[prost(message, repeated, tag = "1")]
    pub placeholders: ::prost::alloc::vec::Vec<PlaceholderValue>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Address {
    #[prost(string, tag = "1")]
    pub ip: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub port: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgBase {
    #[prost(enumeration = "MsgType", tag = "1")]
    pub msg_type: i32,
    #[prost(int64, tag = "2")]
    pub msg_id: i64,
    #[prost(uint64, tag = "3")]
    pub timestamp: u64,
    #[prost(int64, tag = "4")]
    pub source_id: i64,
    #[prost(int64, tag = "5")]
    pub target_id: i64,
    #[prost(map = "string, string", tag = "6")]
    pub properties:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(message, optional, tag = "7")]
    pub replicate_info: ::core::option::Option<ReplicateInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReplicateInfo {
    #[prost(bool, tag = "1")]
    pub is_replicate: bool,
    #[prost(uint64, tag = "2")]
    pub msg_timestamp: u64,
    #[prost(string, tag = "3")]
    pub replicate_id: ::prost::alloc::string::String,
}
/// Don't Modify This. @czs
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgHeader {
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<MsgBase>,
}
/// Don't Modify This. @czs
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DmlMsgHeader {
    #[prost(message, optional, tag = "1")]
    pub base: ::core::option::Option<MsgBase>,
    #[prost(string, tag = "2")]
    pub shard_name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PrivilegeExt {
    #[prost(enumeration = "ObjectType", tag = "1")]
    pub object_type: i32,
    #[prost(enumeration = "ObjectPrivilege", tag = "2")]
    pub object_privilege: i32,
    #[prost(int32, tag = "3")]
    pub object_name_index: i32,
    #[prost(int32, tag = "4")]
    pub object_name_indexs: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SegmentStats {
    #[prost(int64, tag = "1")]
    pub segment_id: i64,
    #[prost(int64, tag = "2")]
    pub num_rows: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientInfo {
    /// sdk_type can be `python`, `golang`, `nodejs` and etc. It's not proper to make `sdk_type` an
    /// enumerate type, since we cannot always update the enum value everytime when newly sdk is supported.
    #[prost(string, tag = "1")]
    pub sdk_type: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub sdk_version: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub local_time: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub user: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub host: ::prost::alloc::string::String,
    /// reserved for newly-added feature if necessary.
    #[prost(map = "string, string", tag = "6")]
    pub reserved:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerInfo {
    #[prost(string, tag = "1")]
    pub build_tags: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub build_time: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub git_commit: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub go_version: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub deploy_mode: ::prost::alloc::string::String,
    /// reserved for newly-added feature if necessary.
    #[prost(map = "string, string", tag = "6")]
    pub reserved:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
/// NodeInfo is used to describe the node information.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NodeInfo {
    #[prost(int64, tag = "1")]
    pub node_id: i64,
    #[prost(string, tag = "2")]
    pub address: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub hostname: ::prost::alloc::string::String,
}
/// ReplicateConfiguration is the configuration that
/// describes the replication topology cross multiple cluster milvus.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReplicateConfiguration {
    #[prost(message, repeated, tag = "1")]
    pub clusters: ::prost::alloc::vec::Vec<MilvusCluster>,
    #[prost(message, repeated, tag = "2")]
    pub cross_cluster_topology: ::prost::alloc::vec::Vec<CrossClusterTopology>,
}
/// ConnectionParam defines the params to connect to the Milvus cluster.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConnectionParam {
    #[prost(string, tag = "1")]
    pub uri: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub token: ::prost::alloc::string::String,
}
/// MilvusCluster describes the Milvus cluster information,
/// including pchannel mapping details.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MilvusCluster {
    #[prost(string, tag = "1")]
    pub cluster_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub connection_param: ::core::option::Option<ConnectionParam>,
    #[prost(string, repeated, tag = "3")]
    pub pchannels: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// CrossClusterTopology is the topology that
/// describes the topology cross multiple cluster milvus.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CrossClusterTopology {
    #[prost(string, tag = "1")]
    pub source_cluster_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub target_cluster_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageId {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(enumeration = "WalName", tag = "2")]
    pub wal_name: i32,
}
/// ImmutableMessage is the message that can not be modified anymore.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ImmutableMessage {
    /// message id
    #[prost(message, optional, tag = "1")]
    pub id: ::core::option::Option<MessageId>,
    /// message body
    #[prost(bytes = "vec", tag = "2")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    /// message properties
    #[prost(map = "string, string", tag = "3")]
    pub properties:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
/// ReplicateCheckpoint is the WAL replicate checkpoint of source cluster.
/// It will be persisted in the target cluster metadata.
/// When a replication started, we will get the replicate checkpoint from target cluster metadata.
/// And use it to continue the replication at source cluster.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReplicateCheckpoint {
    /// the cluster id of source cluster
    #[prost(string, tag = "1")]
    pub cluster_id: ::prost::alloc::string::String,
    /// the pchannel of source cluster
    #[prost(string, tag = "2")]
    pub pchannel: ::prost::alloc::string::String,
    /// the last confirmed message id of the last replicated message
    #[prost(message, optional, tag = "3")]
    pub message_id: ::core::option::Option<MessageId>,
    /// the time tick of the last replicated message
    #[prost(uint64, tag = "4")]
    pub time_tick: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HighlightData {
    #[prost(string, repeated, tag = "1")]
    pub fragments: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(float, repeated, tag = "2")]
    pub scores: ::prost::alloc::vec::Vec<f32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HighlightResult {
    #[prost(string, tag = "1")]
    pub field_name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub datas: ::prost::alloc::vec::Vec<HighlightData>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Highlighter {
    #[prost(enumeration = "HighlightType", tag = "1")]
    pub r#type: i32,
    #[prost(message, repeated, tag = "2")]
    pub params: ::prost::alloc::vec::Vec<KeyValuePair>,
}
/// Deprecated
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ErrorCode {
    Success = 0,
    UnexpectedError = 1,
    ConnectFailed = 2,
    PermissionDenied = 3,
    CollectionNotExists = 4,
    IllegalArgument = 5,
    IllegalDimension = 7,
    IllegalIndexType = 8,
    IllegalCollectionName = 9,
    IllegalTopk = 10,
    IllegalRowRecord = 11,
    IllegalVectorId = 12,
    IllegalSearchResult = 13,
    FileNotFound = 14,
    MetaFailed = 15,
    CacheFailed = 16,
    CannotCreateFolder = 17,
    CannotCreateFile = 18,
    CannotDeleteFolder = 19,
    CannotDeleteFile = 20,
    BuildIndexError = 21,
    IllegalNlist = 22,
    IllegalMetricType = 23,
    OutOfMemory = 24,
    IndexNotExist = 25,
    EmptyCollection = 26,
    UpdateImportTaskFailure = 27,
    CollectionNameNotFound = 28,
    CreateCredentialFailure = 29,
    UpdateCredentialFailure = 30,
    DeleteCredentialFailure = 31,
    GetCredentialFailure = 32,
    ListCredUsersFailure = 33,
    GetUserFailure = 34,
    CreateRoleFailure = 35,
    DropRoleFailure = 36,
    OperateUserRoleFailure = 37,
    SelectRoleFailure = 38,
    SelectUserFailure = 39,
    SelectResourceFailure = 40,
    OperatePrivilegeFailure = 41,
    SelectGrantFailure = 42,
    RefreshPolicyInfoCacheFailure = 43,
    ListPolicyFailure = 44,
    NotShardLeader = 45,
    NoReplicaAvailable = 46,
    SegmentNotFound = 47,
    ForceDeny = 48,
    RateLimit = 49,
    NodeIdNotMatch = 50,
    UpsertAutoIdTrue = 51,
    InsufficientMemoryToLoad = 52,
    MemoryQuotaExhausted = 53,
    DiskQuotaExhausted = 54,
    TimeTickLongDelay = 55,
    NotReadyServe = 56,
    /// Coord is switching from standby mode to active mode
    NotReadyCoordActivating = 57,
    CreatePrivilegeGroupFailure = 58,
    DropPrivilegeGroupFailure = 59,
    ListPrivilegeGroupsFailure = 60,
    OperatePrivilegeGroupFailure = 61,
    SchemaMismatch = 62,
    /// Service availability.
    /// NA: Not Available.
    DataCoordNa = 100,
    /// internal error code.
    DdRequestRace = 1000,
}
impl ErrorCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Success => "Success",
            Self::UnexpectedError => "UnexpectedError",
            Self::ConnectFailed => "ConnectFailed",
            Self::PermissionDenied => "PermissionDenied",
            Self::CollectionNotExists => "CollectionNotExists",
            Self::IllegalArgument => "IllegalArgument",
            Self::IllegalDimension => "IllegalDimension",
            Self::IllegalIndexType => "IllegalIndexType",
            Self::IllegalCollectionName => "IllegalCollectionName",
            Self::IllegalTopk => "IllegalTOPK",
            Self::IllegalRowRecord => "IllegalRowRecord",
            Self::IllegalVectorId => "IllegalVectorID",
            Self::IllegalSearchResult => "IllegalSearchResult",
            Self::FileNotFound => "FileNotFound",
            Self::MetaFailed => "MetaFailed",
            Self::CacheFailed => "CacheFailed",
            Self::CannotCreateFolder => "CannotCreateFolder",
            Self::CannotCreateFile => "CannotCreateFile",
            Self::CannotDeleteFolder => "CannotDeleteFolder",
            Self::CannotDeleteFile => "CannotDeleteFile",
            Self::BuildIndexError => "BuildIndexError",
            Self::IllegalNlist => "IllegalNLIST",
            Self::IllegalMetricType => "IllegalMetricType",
            Self::OutOfMemory => "OutOfMemory",
            Self::IndexNotExist => "IndexNotExist",
            Self::EmptyCollection => "EmptyCollection",
            Self::UpdateImportTaskFailure => "UpdateImportTaskFailure",
            Self::CollectionNameNotFound => "CollectionNameNotFound",
            Self::CreateCredentialFailure => "CreateCredentialFailure",
            Self::UpdateCredentialFailure => "UpdateCredentialFailure",
            Self::DeleteCredentialFailure => "DeleteCredentialFailure",
            Self::GetCredentialFailure => "GetCredentialFailure",
            Self::ListCredUsersFailure => "ListCredUsersFailure",
            Self::GetUserFailure => "GetUserFailure",
            Self::CreateRoleFailure => "CreateRoleFailure",
            Self::DropRoleFailure => "DropRoleFailure",
            Self::OperateUserRoleFailure => "OperateUserRoleFailure",
            Self::SelectRoleFailure => "SelectRoleFailure",
            Self::SelectUserFailure => "SelectUserFailure",
            Self::SelectResourceFailure => "SelectResourceFailure",
            Self::OperatePrivilegeFailure => "OperatePrivilegeFailure",
            Self::SelectGrantFailure => "SelectGrantFailure",
            Self::RefreshPolicyInfoCacheFailure => "RefreshPolicyInfoCacheFailure",
            Self::ListPolicyFailure => "ListPolicyFailure",
            Self::NotShardLeader => "NotShardLeader",
            Self::NoReplicaAvailable => "NoReplicaAvailable",
            Self::SegmentNotFound => "SegmentNotFound",
            Self::ForceDeny => "ForceDeny",
            Self::RateLimit => "RateLimit",
            Self::NodeIdNotMatch => "NodeIDNotMatch",
            Self::UpsertAutoIdTrue => "UpsertAutoIDTrue",
            Self::InsufficientMemoryToLoad => "InsufficientMemoryToLoad",
            Self::MemoryQuotaExhausted => "MemoryQuotaExhausted",
            Self::DiskQuotaExhausted => "DiskQuotaExhausted",
            Self::TimeTickLongDelay => "TimeTickLongDelay",
            Self::NotReadyServe => "NotReadyServe",
            Self::NotReadyCoordActivating => "NotReadyCoordActivating",
            Self::CreatePrivilegeGroupFailure => "CreatePrivilegeGroupFailure",
            Self::DropPrivilegeGroupFailure => "DropPrivilegeGroupFailure",
            Self::ListPrivilegeGroupsFailure => "ListPrivilegeGroupsFailure",
            Self::OperatePrivilegeGroupFailure => "OperatePrivilegeGroupFailure",
            Self::SchemaMismatch => "SchemaMismatch",
            Self::DataCoordNa => "DataCoordNA",
            Self::DdRequestRace => "DDRequestRace",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Success" => Some(Self::Success),
            "UnexpectedError" => Some(Self::UnexpectedError),
            "ConnectFailed" => Some(Self::ConnectFailed),
            "PermissionDenied" => Some(Self::PermissionDenied),
            "CollectionNotExists" => Some(Self::CollectionNotExists),
            "IllegalArgument" => Some(Self::IllegalArgument),
            "IllegalDimension" => Some(Self::IllegalDimension),
            "IllegalIndexType" => Some(Self::IllegalIndexType),
            "IllegalCollectionName" => Some(Self::IllegalCollectionName),
            "IllegalTOPK" => Some(Self::IllegalTopk),
            "IllegalRowRecord" => Some(Self::IllegalRowRecord),
            "IllegalVectorID" => Some(Self::IllegalVectorId),
            "IllegalSearchResult" => Some(Self::IllegalSearchResult),
            "FileNotFound" => Some(Self::FileNotFound),
            "MetaFailed" => Some(Self::MetaFailed),
            "CacheFailed" => Some(Self::CacheFailed),
            "CannotCreateFolder" => Some(Self::CannotCreateFolder),
            "CannotCreateFile" => Some(Self::CannotCreateFile),
            "CannotDeleteFolder" => Some(Self::CannotDeleteFolder),
            "CannotDeleteFile" => Some(Self::CannotDeleteFile),
            "BuildIndexError" => Some(Self::BuildIndexError),
            "IllegalNLIST" => Some(Self::IllegalNlist),
            "IllegalMetricType" => Some(Self::IllegalMetricType),
            "OutOfMemory" => Some(Self::OutOfMemory),
            "IndexNotExist" => Some(Self::IndexNotExist),
            "EmptyCollection" => Some(Self::EmptyCollection),
            "UpdateImportTaskFailure" => Some(Self::UpdateImportTaskFailure),
            "CollectionNameNotFound" => Some(Self::CollectionNameNotFound),
            "CreateCredentialFailure" => Some(Self::CreateCredentialFailure),
            "UpdateCredentialFailure" => Some(Self::UpdateCredentialFailure),
            "DeleteCredentialFailure" => Some(Self::DeleteCredentialFailure),
            "GetCredentialFailure" => Some(Self::GetCredentialFailure),
            "ListCredUsersFailure" => Some(Self::ListCredUsersFailure),
            "GetUserFailure" => Some(Self::GetUserFailure),
            "CreateRoleFailure" => Some(Self::CreateRoleFailure),
            "DropRoleFailure" => Some(Self::DropRoleFailure),
            "OperateUserRoleFailure" => Some(Self::OperateUserRoleFailure),
            "SelectRoleFailure" => Some(Self::SelectRoleFailure),
            "SelectUserFailure" => Some(Self::SelectUserFailure),
            "SelectResourceFailure" => Some(Self::SelectResourceFailure),
            "OperatePrivilegeFailure" => Some(Self::OperatePrivilegeFailure),
            "SelectGrantFailure" => Some(Self::SelectGrantFailure),
            "RefreshPolicyInfoCacheFailure" => Some(Self::RefreshPolicyInfoCacheFailure),
            "ListPolicyFailure" => Some(Self::ListPolicyFailure),
            "NotShardLeader" => Some(Self::NotShardLeader),
            "NoReplicaAvailable" => Some(Self::NoReplicaAvailable),
            "SegmentNotFound" => Some(Self::SegmentNotFound),
            "ForceDeny" => Some(Self::ForceDeny),
            "RateLimit" => Some(Self::RateLimit),
            "NodeIDNotMatch" => Some(Self::NodeIdNotMatch),
            "UpsertAutoIDTrue" => Some(Self::UpsertAutoIdTrue),
            "InsufficientMemoryToLoad" => Some(Self::InsufficientMemoryToLoad),
            "MemoryQuotaExhausted" => Some(Self::MemoryQuotaExhausted),
            "DiskQuotaExhausted" => Some(Self::DiskQuotaExhausted),
            "TimeTickLongDelay" => Some(Self::TimeTickLongDelay),
            "NotReadyServe" => Some(Self::NotReadyServe),
            "NotReadyCoordActivating" => Some(Self::NotReadyCoordActivating),
            "CreatePrivilegeGroupFailure" => Some(Self::CreatePrivilegeGroupFailure),
            "DropPrivilegeGroupFailure" => Some(Self::DropPrivilegeGroupFailure),
            "ListPrivilegeGroupsFailure" => Some(Self::ListPrivilegeGroupsFailure),
            "OperatePrivilegeGroupFailure" => Some(Self::OperatePrivilegeGroupFailure),
            "SchemaMismatch" => Some(Self::SchemaMismatch),
            "DataCoordNA" => Some(Self::DataCoordNa),
            "DDRequestRace" => Some(Self::DdRequestRace),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum IndexState {
    None = 0,
    Unissued = 1,
    InProgress = 2,
    Finished = 3,
    Failed = 4,
    Retry = 5,
}
impl IndexState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::None => "IndexStateNone",
            Self::Unissued => "Unissued",
            Self::InProgress => "InProgress",
            Self::Finished => "Finished",
            Self::Failed => "Failed",
            Self::Retry => "Retry",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "IndexStateNone" => Some(Self::None),
            "Unissued" => Some(Self::Unissued),
            "InProgress" => Some(Self::InProgress),
            "Finished" => Some(Self::Finished),
            "Failed" => Some(Self::Failed),
            "Retry" => Some(Self::Retry),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SegmentState {
    None = 0,
    NotExist = 1,
    Growing = 2,
    Sealed = 3,
    Flushed = 4,
    Flushing = 5,
    Dropped = 6,
    Importing = 7,
}
impl SegmentState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::None => "SegmentStateNone",
            Self::NotExist => "NotExist",
            Self::Growing => "Growing",
            Self::Sealed => "Sealed",
            Self::Flushed => "Flushed",
            Self::Flushing => "Flushing",
            Self::Dropped => "Dropped",
            Self::Importing => "Importing",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SegmentStateNone" => Some(Self::None),
            "NotExist" => Some(Self::NotExist),
            "Growing" => Some(Self::Growing),
            "Sealed" => Some(Self::Sealed),
            "Flushed" => Some(Self::Flushed),
            "Flushing" => Some(Self::Flushing),
            "Dropped" => Some(Self::Dropped),
            "Importing" => Some(Self::Importing),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SegmentLevel {
    /// zero value for legacy logic
    Legacy = 0,
    /// L0 segment, contains delta data for current channel
    L0 = 1,
    /// L1 segment, normal segment, with no extra compaction attribute
    L1 = 2,
    /// L2 segment, segment with extra data distribution info
    L2 = 3,
}
impl SegmentLevel {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Legacy => "Legacy",
            Self::L0 => "L0",
            Self::L1 => "L1",
            Self::L2 => "L2",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Legacy" => Some(Self::Legacy),
            "L0" => Some(Self::L0),
            "L1" => Some(Self::L1),
            "L2" => Some(Self::L2),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PlaceholderType {
    None = 0,
    BinaryVector = 100,
    FloatVector = 101,
    Float16Vector = 102,
    BFloat16Vector = 103,
    SparseFloatVector = 104,
    Int8Vector = 105,
    Int64 = 5,
    VarChar = 21,
    EmbListBinaryVector = 300,
    EmbListFloatVector = 301,
    EmbListFloat16Vector = 302,
    EmbListBFloat16Vector = 303,
    EmbListSparseFloatVector = 304,
    EmbListInt8Vector = 305,
}
impl PlaceholderType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::None => "None",
            Self::BinaryVector => "BinaryVector",
            Self::FloatVector => "FloatVector",
            Self::Float16Vector => "Float16Vector",
            Self::BFloat16Vector => "BFloat16Vector",
            Self::SparseFloatVector => "SparseFloatVector",
            Self::Int8Vector => "Int8Vector",
            Self::Int64 => "Int64",
            Self::VarChar => "VarChar",
            Self::EmbListBinaryVector => "EmbListBinaryVector",
            Self::EmbListFloatVector => "EmbListFloatVector",
            Self::EmbListFloat16Vector => "EmbListFloat16Vector",
            Self::EmbListBFloat16Vector => "EmbListBFloat16Vector",
            Self::EmbListSparseFloatVector => "EmbListSparseFloatVector",
            Self::EmbListInt8Vector => "EmbListInt8Vector",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "None" => Some(Self::None),
            "BinaryVector" => Some(Self::BinaryVector),
            "FloatVector" => Some(Self::FloatVector),
            "Float16Vector" => Some(Self::Float16Vector),
            "BFloat16Vector" => Some(Self::BFloat16Vector),
            "SparseFloatVector" => Some(Self::SparseFloatVector),
            "Int8Vector" => Some(Self::Int8Vector),
            "Int64" => Some(Self::Int64),
            "VarChar" => Some(Self::VarChar),
            "EmbListBinaryVector" => Some(Self::EmbListBinaryVector),
            "EmbListFloatVector" => Some(Self::EmbListFloatVector),
            "EmbListFloat16Vector" => Some(Self::EmbListFloat16Vector),
            "EmbListBFloat16Vector" => Some(Self::EmbListBFloat16Vector),
            "EmbListSparseFloatVector" => Some(Self::EmbListSparseFloatVector),
            "EmbListInt8Vector" => Some(Self::EmbListInt8Vector),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MsgType {
    Undefined = 0,
    /// DEFINITION REQUESTS: COLLECTION
    CreateCollection = 100,
    DropCollection = 101,
    HasCollection = 102,
    DescribeCollection = 103,
    ShowCollections = 104,
    GetSystemConfigs = 105,
    LoadCollection = 106,
    ReleaseCollection = 107,
    CreateAlias = 108,
    DropAlias = 109,
    AlterAlias = 110,
    AlterCollection = 111,
    RenameCollection = 112,
    DescribeAlias = 113,
    ListAliases = 114,
    AlterCollectionField = 115,
    AddCollectionFunction = 116,
    AlterCollectionFunction = 117,
    DropCollectionFunction = 118,
    TruncateCollection = 119,
    /// DEFINITION REQUESTS: PARTITION
    CreatePartition = 200,
    DropPartition = 201,
    HasPartition = 202,
    DescribePartition = 203,
    ShowPartitions = 204,
    LoadPartitions = 205,
    ReleasePartitions = 206,
    /// DEFINE REQUESTS: SEGMENT
    ShowSegments = 250,
    DescribeSegment = 251,
    LoadSegments = 252,
    ReleaseSegments = 253,
    HandoffSegments = 254,
    LoadBalanceSegments = 255,
    DescribeSegments = 256,
    FederListIndexedSegment = 257,
    FederDescribeSegmentIndexData = 258,
    /// DEFINITION REQUESTS: INDEX
    CreateIndex = 300,
    DescribeIndex = 301,
    DropIndex = 302,
    GetIndexStatistics = 303,
    AlterIndex = 304,
    /// MANIPULATION REQUESTS
    Insert = 400,
    Delete = 401,
    Flush = 402,
    ResendSegmentStats = 403,
    Upsert = 404,
    /// streaming service new msg type for internal usage compatible
    ManualFlush = 405,
    /// streaming service new msg type for internal usage compatible
    FlushSegment = 406,
    /// streaming service new msg type for internal usage compatible
    CreateSegment = 407,
    Import = 408,
    /// streaming service new msg type for internal usage compatible
    FlushAll = 409,
    /// QUERY
    Search = 500,
    SearchResult = 501,
    GetIndexState = 502,
    GetIndexBuildProgress = 503,
    GetCollectionStatistics = 504,
    GetPartitionStatistics = 505,
    Retrieve = 506,
    RetrieveResult = 507,
    WatchDmChannels = 508,
    RemoveDmChannels = 509,
    WatchQueryChannels = 510,
    RemoveQueryChannels = 511,
    SealedSegmentsChangeInfo = 512,
    WatchDeltaChannels = 513,
    GetShardLeaders = 514,
    GetReplicas = 515,
    UnsubDmChannel = 516,
    GetDistribution = 517,
    SyncDistribution = 518,
    RunAnalyzer = 519,
    /// DATA SERVICE
    SegmentInfo = 600,
    SystemInfo = 601,
    GetRecoveryInfo = 602,
    GetSegmentState = 603,
    /// SYSTEM CONTROL
    TimeTick = 1200,
    /// GOOSE TODO: Remove kQueryNodeStats
    QueryNodeStats = 1201,
    LoadIndex = 1202,
    RequestId = 1203,
    RequestTso = 1204,
    AllocateSegment = 1205,
    SegmentStatistics = 1206,
    SegmentFlushDone = 1207,
    DataNodeTt = 1208,
    Connect = 1209,
    ListClientInfos = 1210,
    AllocTimestamp = 1211,
    Replicate = 1212,
    /// Credential
    CreateCredential = 1500,
    GetCredential = 1501,
    DeleteCredential = 1502,
    UpdateCredential = 1503,
    ListCredUsernames = 1504,
    /// RBAC
    CreateRole = 1600,
    DropRole = 1601,
    OperateUserRole = 1602,
    SelectRole = 1603,
    SelectUser = 1604,
    SelectResource = 1605,
    OperatePrivilege = 1606,
    SelectGrant = 1607,
    RefreshPolicyInfoCache = 1608,
    ListPolicy = 1609,
    CreatePrivilegeGroup = 1610,
    DropPrivilegeGroup = 1611,
    ListPrivilegeGroups = 1612,
    OperatePrivilegeGroup = 1613,
    OperatePrivilegeV2 = 1614,
    /// Resource group
    CreateResourceGroup = 1700,
    DropResourceGroup = 1701,
    ListResourceGroups = 1702,
    DescribeResourceGroup = 1703,
    TransferNode = 1704,
    TransferReplica = 1705,
    UpdateResourceGroups = 1706,
    /// Database group
    CreateDatabase = 1801,
    DropDatabase = 1802,
    ListDatabases = 1803,
    AlterDatabase = 1804,
    DescribeDatabase = 1805,
    AddCollectionField = 1900,
    /// WAL group
    AlterWal = 2000,
}
impl MsgType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Undefined => "Undefined",
            Self::CreateCollection => "CreateCollection",
            Self::DropCollection => "DropCollection",
            Self::HasCollection => "HasCollection",
            Self::DescribeCollection => "DescribeCollection",
            Self::ShowCollections => "ShowCollections",
            Self::GetSystemConfigs => "GetSystemConfigs",
            Self::LoadCollection => "LoadCollection",
            Self::ReleaseCollection => "ReleaseCollection",
            Self::CreateAlias => "CreateAlias",
            Self::DropAlias => "DropAlias",
            Self::AlterAlias => "AlterAlias",
            Self::AlterCollection => "AlterCollection",
            Self::RenameCollection => "RenameCollection",
            Self::DescribeAlias => "DescribeAlias",
            Self::ListAliases => "ListAliases",
            Self::AlterCollectionField => "AlterCollectionField",
            Self::AddCollectionFunction => "AddCollectionFunction",
            Self::AlterCollectionFunction => "AlterCollectionFunction",
            Self::DropCollectionFunction => "DropCollectionFunction",
            Self::TruncateCollection => "TruncateCollection",
            Self::CreatePartition => "CreatePartition",
            Self::DropPartition => "DropPartition",
            Self::HasPartition => "HasPartition",
            Self::DescribePartition => "DescribePartition",
            Self::ShowPartitions => "ShowPartitions",
            Self::LoadPartitions => "LoadPartitions",
            Self::ReleasePartitions => "ReleasePartitions",
            Self::ShowSegments => "ShowSegments",
            Self::DescribeSegment => "DescribeSegment",
            Self::LoadSegments => "LoadSegments",
            Self::ReleaseSegments => "ReleaseSegments",
            Self::HandoffSegments => "HandoffSegments",
            Self::LoadBalanceSegments => "LoadBalanceSegments",
            Self::DescribeSegments => "DescribeSegments",
            Self::FederListIndexedSegment => "FederListIndexedSegment",
            Self::FederDescribeSegmentIndexData => "FederDescribeSegmentIndexData",
            Self::CreateIndex => "CreateIndex",
            Self::DescribeIndex => "DescribeIndex",
            Self::DropIndex => "DropIndex",
            Self::GetIndexStatistics => "GetIndexStatistics",
            Self::AlterIndex => "AlterIndex",
            Self::Insert => "Insert",
            Self::Delete => "Delete",
            Self::Flush => "Flush",
            Self::ResendSegmentStats => "ResendSegmentStats",
            Self::Upsert => "Upsert",
            Self::ManualFlush => "ManualFlush",
            Self::FlushSegment => "FlushSegment",
            Self::CreateSegment => "CreateSegment",
            Self::Import => "Import",
            Self::FlushAll => "FlushAll",
            Self::Search => "Search",
            Self::SearchResult => "SearchResult",
            Self::GetIndexState => "GetIndexState",
            Self::GetIndexBuildProgress => "GetIndexBuildProgress",
            Self::GetCollectionStatistics => "GetCollectionStatistics",
            Self::GetPartitionStatistics => "GetPartitionStatistics",
            Self::Retrieve => "Retrieve",
            Self::RetrieveResult => "RetrieveResult",
            Self::WatchDmChannels => "WatchDmChannels",
            Self::RemoveDmChannels => "RemoveDmChannels",
            Self::WatchQueryChannels => "WatchQueryChannels",
            Self::RemoveQueryChannels => "RemoveQueryChannels",
            Self::SealedSegmentsChangeInfo => "SealedSegmentsChangeInfo",
            Self::WatchDeltaChannels => "WatchDeltaChannels",
            Self::GetShardLeaders => "GetShardLeaders",
            Self::GetReplicas => "GetReplicas",
            Self::UnsubDmChannel => "UnsubDmChannel",
            Self::GetDistribution => "GetDistribution",
            Self::SyncDistribution => "SyncDistribution",
            Self::RunAnalyzer => "RunAnalyzer",
            Self::SegmentInfo => "SegmentInfo",
            Self::SystemInfo => "SystemInfo",
            Self::GetRecoveryInfo => "GetRecoveryInfo",
            Self::GetSegmentState => "GetSegmentState",
            Self::TimeTick => "TimeTick",
            Self::QueryNodeStats => "QueryNodeStats",
            Self::LoadIndex => "LoadIndex",
            Self::RequestId => "RequestID",
            Self::RequestTso => "RequestTSO",
            Self::AllocateSegment => "AllocateSegment",
            Self::SegmentStatistics => "SegmentStatistics",
            Self::SegmentFlushDone => "SegmentFlushDone",
            Self::DataNodeTt => "DataNodeTt",
            Self::Connect => "Connect",
            Self::ListClientInfos => "ListClientInfos",
            Self::AllocTimestamp => "AllocTimestamp",
            Self::Replicate => "Replicate",
            Self::CreateCredential => "CreateCredential",
            Self::GetCredential => "GetCredential",
            Self::DeleteCredential => "DeleteCredential",
            Self::UpdateCredential => "UpdateCredential",
            Self::ListCredUsernames => "ListCredUsernames",
            Self::CreateRole => "CreateRole",
            Self::DropRole => "DropRole",
            Self::OperateUserRole => "OperateUserRole",
            Self::SelectRole => "SelectRole",
            Self::SelectUser => "SelectUser",
            Self::SelectResource => "SelectResource",
            Self::OperatePrivilege => "OperatePrivilege",
            Self::SelectGrant => "SelectGrant",
            Self::RefreshPolicyInfoCache => "RefreshPolicyInfoCache",
            Self::ListPolicy => "ListPolicy",
            Self::CreatePrivilegeGroup => "CreatePrivilegeGroup",
            Self::DropPrivilegeGroup => "DropPrivilegeGroup",
            Self::ListPrivilegeGroups => "ListPrivilegeGroups",
            Self::OperatePrivilegeGroup => "OperatePrivilegeGroup",
            Self::OperatePrivilegeV2 => "OperatePrivilegeV2",
            Self::CreateResourceGroup => "CreateResourceGroup",
            Self::DropResourceGroup => "DropResourceGroup",
            Self::ListResourceGroups => "ListResourceGroups",
            Self::DescribeResourceGroup => "DescribeResourceGroup",
            Self::TransferNode => "TransferNode",
            Self::TransferReplica => "TransferReplica",
            Self::UpdateResourceGroups => "UpdateResourceGroups",
            Self::CreateDatabase => "CreateDatabase",
            Self::DropDatabase => "DropDatabase",
            Self::ListDatabases => "ListDatabases",
            Self::AlterDatabase => "AlterDatabase",
            Self::DescribeDatabase => "DescribeDatabase",
            Self::AddCollectionField => "AddCollectionField",
            Self::AlterWal => "AlterWAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Undefined" => Some(Self::Undefined),
            "CreateCollection" => Some(Self::CreateCollection),
            "DropCollection" => Some(Self::DropCollection),
            "HasCollection" => Some(Self::HasCollection),
            "DescribeCollection" => Some(Self::DescribeCollection),
            "ShowCollections" => Some(Self::ShowCollections),
            "GetSystemConfigs" => Some(Self::GetSystemConfigs),
            "LoadCollection" => Some(Self::LoadCollection),
            "ReleaseCollection" => Some(Self::ReleaseCollection),
            "CreateAlias" => Some(Self::CreateAlias),
            "DropAlias" => Some(Self::DropAlias),
            "AlterAlias" => Some(Self::AlterAlias),
            "AlterCollection" => Some(Self::AlterCollection),
            "RenameCollection" => Some(Self::RenameCollection),
            "DescribeAlias" => Some(Self::DescribeAlias),
            "ListAliases" => Some(Self::ListAliases),
            "AlterCollectionField" => Some(Self::AlterCollectionField),
            "AddCollectionFunction" => Some(Self::AddCollectionFunction),
            "AlterCollectionFunction" => Some(Self::AlterCollectionFunction),
            "DropCollectionFunction" => Some(Self::DropCollectionFunction),
            "TruncateCollection" => Some(Self::TruncateCollection),
            "CreatePartition" => Some(Self::CreatePartition),
            "DropPartition" => Some(Self::DropPartition),
            "HasPartition" => Some(Self::HasPartition),
            "DescribePartition" => Some(Self::DescribePartition),
            "ShowPartitions" => Some(Self::ShowPartitions),
            "LoadPartitions" => Some(Self::LoadPartitions),
            "ReleasePartitions" => Some(Self::ReleasePartitions),
            "ShowSegments" => Some(Self::ShowSegments),
            "DescribeSegment" => Some(Self::DescribeSegment),
            "LoadSegments" => Some(Self::LoadSegments),
            "ReleaseSegments" => Some(Self::ReleaseSegments),
            "HandoffSegments" => Some(Self::HandoffSegments),
            "LoadBalanceSegments" => Some(Self::LoadBalanceSegments),
            "DescribeSegments" => Some(Self::DescribeSegments),
            "FederListIndexedSegment" => Some(Self::FederListIndexedSegment),
            "FederDescribeSegmentIndexData" => Some(Self::FederDescribeSegmentIndexData),
            "CreateIndex" => Some(Self::CreateIndex),
            "DescribeIndex" => Some(Self::DescribeIndex),
            "DropIndex" => Some(Self::DropIndex),
            "GetIndexStatistics" => Some(Self::GetIndexStatistics),
            "AlterIndex" => Some(Self::AlterIndex),
            "Insert" => Some(Self::Insert),
            "Delete" => Some(Self::Delete),
            "Flush" => Some(Self::Flush),
            "ResendSegmentStats" => Some(Self::ResendSegmentStats),
            "Upsert" => Some(Self::Upsert),
            "ManualFlush" => Some(Self::ManualFlush),
            "FlushSegment" => Some(Self::FlushSegment),
            "CreateSegment" => Some(Self::CreateSegment),
            "Import" => Some(Self::Import),
            "FlushAll" => Some(Self::FlushAll),
            "Search" => Some(Self::Search),
            "SearchResult" => Some(Self::SearchResult),
            "GetIndexState" => Some(Self::GetIndexState),
            "GetIndexBuildProgress" => Some(Self::GetIndexBuildProgress),
            "GetCollectionStatistics" => Some(Self::GetCollectionStatistics),
            "GetPartitionStatistics" => Some(Self::GetPartitionStatistics),
            "Retrieve" => Some(Self::Retrieve),
            "RetrieveResult" => Some(Self::RetrieveResult),
            "WatchDmChannels" => Some(Self::WatchDmChannels),
            "RemoveDmChannels" => Some(Self::RemoveDmChannels),
            "WatchQueryChannels" => Some(Self::WatchQueryChannels),
            "RemoveQueryChannels" => Some(Self::RemoveQueryChannels),
            "SealedSegmentsChangeInfo" => Some(Self::SealedSegmentsChangeInfo),
            "WatchDeltaChannels" => Some(Self::WatchDeltaChannels),
            "GetShardLeaders" => Some(Self::GetShardLeaders),
            "GetReplicas" => Some(Self::GetReplicas),
            "UnsubDmChannel" => Some(Self::UnsubDmChannel),
            "GetDistribution" => Some(Self::GetDistribution),
            "SyncDistribution" => Some(Self::SyncDistribution),
            "RunAnalyzer" => Some(Self::RunAnalyzer),
            "SegmentInfo" => Some(Self::SegmentInfo),
            "SystemInfo" => Some(Self::SystemInfo),
            "GetRecoveryInfo" => Some(Self::GetRecoveryInfo),
            "GetSegmentState" => Some(Self::GetSegmentState),
            "TimeTick" => Some(Self::TimeTick),
            "QueryNodeStats" => Some(Self::QueryNodeStats),
            "LoadIndex" => Some(Self::LoadIndex),
            "RequestID" => Some(Self::RequestId),
            "RequestTSO" => Some(Self::RequestTso),
            "AllocateSegment" => Some(Self::AllocateSegment),
            "SegmentStatistics" => Some(Self::SegmentStatistics),
            "SegmentFlushDone" => Some(Self::SegmentFlushDone),
            "DataNodeTt" => Some(Self::DataNodeTt),
            "Connect" => Some(Self::Connect),
            "ListClientInfos" => Some(Self::ListClientInfos),
            "AllocTimestamp" => Some(Self::AllocTimestamp),
            "Replicate" => Some(Self::Replicate),
            "CreateCredential" => Some(Self::CreateCredential),
            "GetCredential" => Some(Self::GetCredential),
            "DeleteCredential" => Some(Self::DeleteCredential),
            "UpdateCredential" => Some(Self::UpdateCredential),
            "ListCredUsernames" => Some(Self::ListCredUsernames),
            "CreateRole" => Some(Self::CreateRole),
            "DropRole" => Some(Self::DropRole),
            "OperateUserRole" => Some(Self::OperateUserRole),
            "SelectRole" => Some(Self::SelectRole),
            "SelectUser" => Some(Self::SelectUser),
            "SelectResource" => Some(Self::SelectResource),
            "OperatePrivilege" => Some(Self::OperatePrivilege),
            "SelectGrant" => Some(Self::SelectGrant),
            "RefreshPolicyInfoCache" => Some(Self::RefreshPolicyInfoCache),
            "ListPolicy" => Some(Self::ListPolicy),
            "CreatePrivilegeGroup" => Some(Self::CreatePrivilegeGroup),
            "DropPrivilegeGroup" => Some(Self::DropPrivilegeGroup),
            "ListPrivilegeGroups" => Some(Self::ListPrivilegeGroups),
            "OperatePrivilegeGroup" => Some(Self::OperatePrivilegeGroup),
            "OperatePrivilegeV2" => Some(Self::OperatePrivilegeV2),
            "CreateResourceGroup" => Some(Self::CreateResourceGroup),
            "DropResourceGroup" => Some(Self::DropResourceGroup),
            "ListResourceGroups" => Some(Self::ListResourceGroups),
            "DescribeResourceGroup" => Some(Self::DescribeResourceGroup),
            "TransferNode" => Some(Self::TransferNode),
            "TransferReplica" => Some(Self::TransferReplica),
            "UpdateResourceGroups" => Some(Self::UpdateResourceGroups),
            "CreateDatabase" => Some(Self::CreateDatabase),
            "DropDatabase" => Some(Self::DropDatabase),
            "ListDatabases" => Some(Self::ListDatabases),
            "AlterDatabase" => Some(Self::AlterDatabase),
            "DescribeDatabase" => Some(Self::DescribeDatabase),
            "AddCollectionField" => Some(Self::AddCollectionField),
            "AlterWAL" => Some(Self::AlterWal),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DslType {
    Dsl = 0,
    BoolExprV1 = 1,
}
impl DslType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Dsl => "Dsl",
            Self::BoolExprV1 => "BoolExprV1",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Dsl" => Some(Self::Dsl),
            "BoolExprV1" => Some(Self::BoolExprV1),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CompactionState {
    UndefiedState = 0,
    Executing = 1,
    Completed = 2,
}
impl CompactionState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::UndefiedState => "UndefiedState",
            Self::Executing => "Executing",
            Self::Completed => "Completed",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UndefiedState" => Some(Self::UndefiedState),
            "Executing" => Some(Self::Executing),
            "Completed" => Some(Self::Completed),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ConsistencyLevel {
    Strong = 0,
    /// default in PyMilvus
    Session = 1,
    Bounded = 2,
    Eventually = 3,
    /// Users pass their own `guarantee_timestamp`.
    Customized = 4,
}
impl ConsistencyLevel {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Strong => "Strong",
            Self::Session => "Session",
            Self::Bounded => "Bounded",
            Self::Eventually => "Eventually",
            Self::Customized => "Customized",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Strong" => Some(Self::Strong),
            "Session" => Some(Self::Session),
            "Bounded" => Some(Self::Bounded),
            "Eventually" => Some(Self::Eventually),
            "Customized" => Some(Self::Customized),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ImportState {
    /// the task in in pending list of rootCoord, waiting to be executed
    ImportPending = 0,
    /// the task failed for some reason, get detail reason from GetImportStateResponse.infos
    ImportFailed = 1,
    /// the task has been sent to datanode to execute
    ImportStarted = 2,
    /// all data files have been parsed and all meta data already persisted, ready to be flushed.
    ImportPersisted = 5,
    /// all segments are successfully flushed.
    ImportFlushed = 8,
    /// all indexes are successfully built and segments are able to be compacted as normal.
    ImportCompleted = 6,
    /// the task failed and all segments it generated are cleaned up.
    ImportFailedAndCleaned = 7,
}
impl ImportState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::ImportPending => "ImportPending",
            Self::ImportFailed => "ImportFailed",
            Self::ImportStarted => "ImportStarted",
            Self::ImportPersisted => "ImportPersisted",
            Self::ImportFlushed => "ImportFlushed",
            Self::ImportCompleted => "ImportCompleted",
            Self::ImportFailedAndCleaned => "ImportFailedAndCleaned",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ImportPending" => Some(Self::ImportPending),
            "ImportFailed" => Some(Self::ImportFailed),
            "ImportStarted" => Some(Self::ImportStarted),
            "ImportPersisted" => Some(Self::ImportPersisted),
            "ImportFlushed" => Some(Self::ImportFlushed),
            "ImportCompleted" => Some(Self::ImportCompleted),
            "ImportFailedAndCleaned" => Some(Self::ImportFailedAndCleaned),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ObjectType {
    Collection = 0,
    Global = 1,
    User = 2,
}
impl ObjectType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Collection => "Collection",
            Self::Global => "Global",
            Self::User => "User",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Collection" => Some(Self::Collection),
            "Global" => Some(Self::Global),
            "User" => Some(Self::User),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ObjectPrivilege {
    PrivilegeAll = 0,
    PrivilegeCreateCollection = 1,
    PrivilegeDropCollection = 2,
    PrivilegeDescribeCollection = 3,
    PrivilegeShowCollections = 4,
    PrivilegeLoad = 5,
    PrivilegeRelease = 6,
    PrivilegeCompaction = 7,
    PrivilegeInsert = 8,
    PrivilegeDelete = 9,
    PrivilegeGetStatistics = 10,
    PrivilegeCreateIndex = 11,
    PrivilegeIndexDetail = 12,
    PrivilegeDropIndex = 13,
    PrivilegeSearch = 14,
    PrivilegeFlush = 15,
    PrivilegeQuery = 16,
    PrivilegeLoadBalance = 17,
    PrivilegeImport = 18,
    PrivilegeCreateOwnership = 19,
    PrivilegeUpdateUser = 20,
    PrivilegeDropOwnership = 21,
    PrivilegeSelectOwnership = 22,
    PrivilegeManageOwnership = 23,
    PrivilegeSelectUser = 24,
    PrivilegeUpsert = 25,
    PrivilegeCreateResourceGroup = 26,
    PrivilegeDropResourceGroup = 27,
    PrivilegeDescribeResourceGroup = 28,
    PrivilegeListResourceGroups = 29,
    PrivilegeTransferNode = 30,
    PrivilegeTransferReplica = 31,
    PrivilegeGetLoadingProgress = 32,
    PrivilegeGetLoadState = 33,
    PrivilegeRenameCollection = 34,
    PrivilegeCreateDatabase = 35,
    PrivilegeDropDatabase = 36,
    PrivilegeListDatabases = 37,
    PrivilegeFlushAll = 38,
    PrivilegeCreatePartition = 39,
    PrivilegeDropPartition = 40,
    PrivilegeShowPartitions = 41,
    PrivilegeHasPartition = 42,
    PrivilegeGetFlushState = 43,
    PrivilegeCreateAlias = 44,
    PrivilegeDropAlias = 45,
    PrivilegeDescribeAlias = 46,
    PrivilegeListAliases = 47,
    PrivilegeUpdateResourceGroups = 48,
    PrivilegeAlterDatabase = 49,
    PrivilegeDescribeDatabase = 50,
    PrivilegeBackupRbac = 51,
    PrivilegeRestoreRbac = 52,
    PrivilegeGroupReadOnly = 53,
    PrivilegeGroupReadWrite = 54,
    PrivilegeGroupAdmin = 55,
    PrivilegeCreatePrivilegeGroup = 56,
    PrivilegeDropPrivilegeGroup = 57,
    PrivilegeListPrivilegeGroups = 58,
    PrivilegeOperatePrivilegeGroup = 59,
    PrivilegeGroupClusterReadOnly = 60,
    PrivilegeGroupClusterReadWrite = 61,
    PrivilegeGroupClusterAdmin = 62,
    PrivilegeGroupDatabaseReadOnly = 63,
    PrivilegeGroupDatabaseReadWrite = 64,
    PrivilegeGroupDatabaseAdmin = 65,
    PrivilegeGroupCollectionReadOnly = 66,
    PrivilegeGroupCollectionReadWrite = 67,
    PrivilegeGroupCollectionAdmin = 68,
    PrivilegeGetImportProgress = 69,
    PrivilegeListImport = 70,
    PrivilegeAddCollectionField = 71,
    PrivilegeAddFileResource = 72,
    PrivilegeRemoveFileResource = 73,
    PrivilegeListFileResources = 74,
    PrivilegeUpdateReplicateConfiguration = 78,
    PrivilegeGetReplicateConfiguration = 85,
}
impl ObjectPrivilege {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::PrivilegeAll => "PrivilegeAll",
            Self::PrivilegeCreateCollection => "PrivilegeCreateCollection",
            Self::PrivilegeDropCollection => "PrivilegeDropCollection",
            Self::PrivilegeDescribeCollection => "PrivilegeDescribeCollection",
            Self::PrivilegeShowCollections => "PrivilegeShowCollections",
            Self::PrivilegeLoad => "PrivilegeLoad",
            Self::PrivilegeRelease => "PrivilegeRelease",
            Self::PrivilegeCompaction => "PrivilegeCompaction",
            Self::PrivilegeInsert => "PrivilegeInsert",
            Self::PrivilegeDelete => "PrivilegeDelete",
            Self::PrivilegeGetStatistics => "PrivilegeGetStatistics",
            Self::PrivilegeCreateIndex => "PrivilegeCreateIndex",
            Self::PrivilegeIndexDetail => "PrivilegeIndexDetail",
            Self::PrivilegeDropIndex => "PrivilegeDropIndex",
            Self::PrivilegeSearch => "PrivilegeSearch",
            Self::PrivilegeFlush => "PrivilegeFlush",
            Self::PrivilegeQuery => "PrivilegeQuery",
            Self::PrivilegeLoadBalance => "PrivilegeLoadBalance",
            Self::PrivilegeImport => "PrivilegeImport",
            Self::PrivilegeCreateOwnership => "PrivilegeCreateOwnership",
            Self::PrivilegeUpdateUser => "PrivilegeUpdateUser",
            Self::PrivilegeDropOwnership => "PrivilegeDropOwnership",
            Self::PrivilegeSelectOwnership => "PrivilegeSelectOwnership",
            Self::PrivilegeManageOwnership => "PrivilegeManageOwnership",
            Self::PrivilegeSelectUser => "PrivilegeSelectUser",
            Self::PrivilegeUpsert => "PrivilegeUpsert",
            Self::PrivilegeCreateResourceGroup => "PrivilegeCreateResourceGroup",
            Self::PrivilegeDropResourceGroup => "PrivilegeDropResourceGroup",
            Self::PrivilegeDescribeResourceGroup => "PrivilegeDescribeResourceGroup",
            Self::PrivilegeListResourceGroups => "PrivilegeListResourceGroups",
            Self::PrivilegeTransferNode => "PrivilegeTransferNode",
            Self::PrivilegeTransferReplica => "PrivilegeTransferReplica",
            Self::PrivilegeGetLoadingProgress => "PrivilegeGetLoadingProgress",
            Self::PrivilegeGetLoadState => "PrivilegeGetLoadState",
            Self::PrivilegeRenameCollection => "PrivilegeRenameCollection",
            Self::PrivilegeCreateDatabase => "PrivilegeCreateDatabase",
            Self::PrivilegeDropDatabase => "PrivilegeDropDatabase",
            Self::PrivilegeListDatabases => "PrivilegeListDatabases",
            Self::PrivilegeFlushAll => "PrivilegeFlushAll",
            Self::PrivilegeCreatePartition => "PrivilegeCreatePartition",
            Self::PrivilegeDropPartition => "PrivilegeDropPartition",
            Self::PrivilegeShowPartitions => "PrivilegeShowPartitions",
            Self::PrivilegeHasPartition => "PrivilegeHasPartition",
            Self::PrivilegeGetFlushState => "PrivilegeGetFlushState",
            Self::PrivilegeCreateAlias => "PrivilegeCreateAlias",
            Self::PrivilegeDropAlias => "PrivilegeDropAlias",
            Self::PrivilegeDescribeAlias => "PrivilegeDescribeAlias",
            Self::PrivilegeListAliases => "PrivilegeListAliases",
            Self::PrivilegeUpdateResourceGroups => "PrivilegeUpdateResourceGroups",
            Self::PrivilegeAlterDatabase => "PrivilegeAlterDatabase",
            Self::PrivilegeDescribeDatabase => "PrivilegeDescribeDatabase",
            Self::PrivilegeBackupRbac => "PrivilegeBackupRBAC",
            Self::PrivilegeRestoreRbac => "PrivilegeRestoreRBAC",
            Self::PrivilegeGroupReadOnly => "PrivilegeGroupReadOnly",
            Self::PrivilegeGroupReadWrite => "PrivilegeGroupReadWrite",
            Self::PrivilegeGroupAdmin => "PrivilegeGroupAdmin",
            Self::PrivilegeCreatePrivilegeGroup => "PrivilegeCreatePrivilegeGroup",
            Self::PrivilegeDropPrivilegeGroup => "PrivilegeDropPrivilegeGroup",
            Self::PrivilegeListPrivilegeGroups => "PrivilegeListPrivilegeGroups",
            Self::PrivilegeOperatePrivilegeGroup => "PrivilegeOperatePrivilegeGroup",
            Self::PrivilegeGroupClusterReadOnly => "PrivilegeGroupClusterReadOnly",
            Self::PrivilegeGroupClusterReadWrite => "PrivilegeGroupClusterReadWrite",
            Self::PrivilegeGroupClusterAdmin => "PrivilegeGroupClusterAdmin",
            Self::PrivilegeGroupDatabaseReadOnly => "PrivilegeGroupDatabaseReadOnly",
            Self::PrivilegeGroupDatabaseReadWrite => "PrivilegeGroupDatabaseReadWrite",
            Self::PrivilegeGroupDatabaseAdmin => "PrivilegeGroupDatabaseAdmin",
            Self::PrivilegeGroupCollectionReadOnly => "PrivilegeGroupCollectionReadOnly",
            Self::PrivilegeGroupCollectionReadWrite => {
                "PrivilegeGroupCollectionReadWrite"
            }
            Self::PrivilegeGroupCollectionAdmin => {
                "PrivilegeGroupCollectionAdmin"
            }
            Self::PrivilegeGetImportProgress => "PrivilegeGetImportProgress",
            Self::PrivilegeListImport => "PrivilegeListImport",
            Self::PrivilegeAddCollectionField => "PrivilegeAddCollectionField",
            Self::PrivilegeAddFileResource => "PrivilegeAddFileResource",
            Self::PrivilegeRemoveFileResource => "PrivilegeRemoveFileResource",
            Self::PrivilegeListFileResources => "PrivilegeListFileResources",
            Self::PrivilegeUpdateReplicateConfiguration => {
                "PrivilegeUpdateReplicateConfiguration"
            }
            Self::PrivilegeGetReplicateConfiguration => {
                "PrivilegeGetReplicateConfiguration"
            }
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PrivilegeAll" => Some(Self::PrivilegeAll),
            "PrivilegeCreateCollection" => Some(Self::PrivilegeCreateCollection),
            "PrivilegeDropCollection" => Some(Self::PrivilegeDropCollection),
            "PrivilegeDescribeCollection" => Some(Self::PrivilegeDescribeCollection),
            "PrivilegeShowCollections" => Some(Self::PrivilegeShowCollections),
            "PrivilegeLoad" => Some(Self::PrivilegeLoad),
            "PrivilegeRelease" => Some(Self::PrivilegeRelease),
            "PrivilegeCompaction" => Some(Self::PrivilegeCompaction),
            "PrivilegeInsert" => Some(Self::PrivilegeInsert),
            "PrivilegeDelete" => Some(Self::PrivilegeDelete),
            "PrivilegeGetStatistics" => Some(Self::PrivilegeGetStatistics),
            "PrivilegeCreateIndex" => Some(Self::PrivilegeCreateIndex),
            "PrivilegeIndexDetail" => Some(Self::PrivilegeIndexDetail),
            "PrivilegeDropIndex" => Some(Self::PrivilegeDropIndex),
            "PrivilegeSearch" => Some(Self::PrivilegeSearch),
            "PrivilegeFlush" => Some(Self::PrivilegeFlush),
            "PrivilegeQuery" => Some(Self::PrivilegeQuery),
            "PrivilegeLoadBalance" => Some(Self::PrivilegeLoadBalance),
            "PrivilegeImport" => Some(Self::PrivilegeImport),
            "PrivilegeCreateOwnership" => Some(Self::PrivilegeCreateOwnership),
            "PrivilegeUpdateUser" => Some(Self::PrivilegeUpdateUser),
            "PrivilegeDropOwnership" => Some(Self::PrivilegeDropOwnership),
            "PrivilegeSelectOwnership" => Some(Self::PrivilegeSelectOwnership),
            "PrivilegeManageOwnership" => Some(Self::PrivilegeManageOwnership),
            "PrivilegeSelectUser" => Some(Self::PrivilegeSelectUser),
            "PrivilegeUpsert" => Some(Self::PrivilegeUpsert),
            "PrivilegeCreateResourceGroup" => Some(Self::PrivilegeCreateResourceGroup),
            "PrivilegeDropResourceGroup" => Some(Self::PrivilegeDropResourceGroup),
            "PrivilegeDescribeResourceGroup" => Some(Self::PrivilegeDescribeResourceGroup),
            "PrivilegeListResourceGroups" => Some(Self::PrivilegeListResourceGroups),
            "PrivilegeTransferNode" => Some(Self::PrivilegeTransferNode),
            "PrivilegeTransferReplica" => Some(Self::PrivilegeTransferReplica),
            "PrivilegeGetLoadingProgress" => Some(Self::PrivilegeGetLoadingProgress),
            "PrivilegeGetLoadState" => Some(Self::PrivilegeGetLoadState),
            "PrivilegeRenameCollection" => Some(Self::PrivilegeRenameCollection),
            "PrivilegeCreateDatabase" => Some(Self::PrivilegeCreateDatabase),
            "PrivilegeDropDatabase" => Some(Self::PrivilegeDropDatabase),
            "PrivilegeListDatabases" => Some(Self::PrivilegeListDatabases),
            "PrivilegeFlushAll" => Some(Self::PrivilegeFlushAll),
            "PrivilegeCreatePartition" => Some(Self::PrivilegeCreatePartition),
            "PrivilegeDropPartition" => Some(Self::PrivilegeDropPartition),
            "PrivilegeShowPartitions" => Some(Self::PrivilegeShowPartitions),
            "PrivilegeHasPartition" => Some(Self::PrivilegeHasPartition),
            "PrivilegeGetFlushState" => Some(Self::PrivilegeGetFlushState),
            "PrivilegeCreateAlias" => Some(Self::PrivilegeCreateAlias),
            "PrivilegeDropAlias" => Some(Self::PrivilegeDropAlias),
            "PrivilegeDescribeAlias" => Some(Self::PrivilegeDescribeAlias),
            "PrivilegeListAliases" => Some(Self::PrivilegeListAliases),
            "PrivilegeUpdateResourceGroups" => Some(Self::PrivilegeUpdateResourceGroups),
            "PrivilegeAlterDatabase" => Some(Self::PrivilegeAlterDatabase),
            "PrivilegeDescribeDatabase" => Some(Self::PrivilegeDescribeDatabase),
            "PrivilegeBackupRBAC" => Some(Self::PrivilegeBackupRbac),
            "PrivilegeRestoreRBAC" => Some(Self::PrivilegeRestoreRbac),
            "PrivilegeGroupReadOnly" => Some(Self::PrivilegeGroupReadOnly),
            "PrivilegeGroupReadWrite" => Some(Self::PrivilegeGroupReadWrite),
            "PrivilegeGroupAdmin" => Some(Self::PrivilegeGroupAdmin),
            "PrivilegeCreatePrivilegeGroup" => Some(Self::PrivilegeCreatePrivilegeGroup),
            "PrivilegeDropPrivilegeGroup" => Some(Self::PrivilegeDropPrivilegeGroup),
            "PrivilegeListPrivilegeGroups" => Some(Self::PrivilegeListPrivilegeGroups),
            "PrivilegeOperatePrivilegeGroup" => {
                Some(Self::PrivilegeOperatePrivilegeGroup)
            }
            "PrivilegeGroupClusterReadOnly" => Some(Self::PrivilegeGroupClusterReadOnly),
            "PrivilegeGroupClusterReadWrite" => {
                Some(Self::PrivilegeGroupClusterReadWrite)
            }
            "PrivilegeGroupClusterAdmin" => Some(Self::PrivilegeGroupClusterAdmin),
            "PrivilegeGroupDatabaseReadOnly" => {
                Some(Self::PrivilegeGroupDatabaseReadOnly)
            }
            "PrivilegeGroupDatabaseReadWrite" => {
                Some(Self::PrivilegeGroupDatabaseReadWrite)
            }
            "PrivilegeGroupDatabaseAdmin" => Some(Self::PrivilegeGroupDatabaseAdmin),
            "PrivilegeGroupCollectionReadOnly" => {
                Some(Self::PrivilegeGroupCollectionReadOnly)
            }
            "PrivilegeGroupCollectionReadWrite" => {
                Some(Self::PrivilegeGroupCollectionReadWrite)
            }
            "PrivilegeGroupCollectionAdmin" => Some(Self::PrivilegeGroupCollectionAdmin),
            "PrivilegeGetImportProgress" => Some(Self::PrivilegeGetImportProgress),
            "PrivilegeListImport" => Some(Self::PrivilegeListImport),
            "PrivilegeAddCollectionField" => Some(Self::PrivilegeAddCollectionField),
            "PrivilegeAddFileResource" => Some(Self::PrivilegeAddFileResource),
            "PrivilegeRemoveFileResource" => Some(Self::PrivilegeRemoveFileResource),
            "PrivilegeListFileResources" => Some(Self::PrivilegeListFileResources),
            "PrivilegeUpdateReplicateConfiguration" => {
                Some(Self::PrivilegeUpdateReplicateConfiguration)
            }
            "PrivilegeGetReplicateConfiguration" => {
                Some(Self::PrivilegeGetReplicateConfiguration)
            }
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum StateCode {
    Initializing = 0,
    Healthy = 1,
    Abnormal = 2,
    StandBy = 3,
    Stopping = 4,
}
impl StateCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Initializing => "Initializing",
            Self::Healthy => "Healthy",
            Self::Abnormal => "Abnormal",
            Self::StandBy => "StandBy",
            Self::Stopping => "Stopping",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Initializing" => Some(Self::Initializing),
            "Healthy" => Some(Self::Healthy),
            "Abnormal" => Some(Self::Abnormal),
            "StandBy" => Some(Self::StandBy),
            "Stopping" => Some(Self::Stopping),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum LoadState {
    NotExist = 0,
    NotLoad = 1,
    Loading = 2,
    Loaded = 3,
}
impl LoadState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::NotExist => "LoadStateNotExist",
            Self::NotLoad => "LoadStateNotLoad",
            Self::Loading => "LoadStateLoading",
            Self::Loaded => "LoadStateLoaded",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LoadStateNotExist" => Some(Self::NotExist),
            "LoadStateNotLoad" => Some(Self::NotLoad),
            "LoadStateLoading" => Some(Self::Loading),
            "LoadStateLoaded" => Some(Self::Loaded),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum LoadPriority {
    High = 0,
    Low = 1,
}
impl LoadPriority {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::High => "HIGH",
            Self::Low => "LOW",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "HIGH" => Some(Self::High),
            "LOW" => Some(Self::Low),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum WalName {
    Unknown = 0,
    RocksMq = 1,
    Pulsar = 2,
    Kafka = 3,
    WoodPecker = 4,
    Test = 999,
}
impl WalName {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "Unknown",
            Self::RocksMq => "RocksMQ",
            Self::Pulsar => "Pulsar",
            Self::Kafka => "Kafka",
            Self::WoodPecker => "WoodPecker",
            Self::Test => "Test",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Unknown" => Some(Self::Unknown),
            "RocksMQ" => Some(Self::RocksMq),
            "Pulsar" => Some(Self::Pulsar),
            "Kafka" => Some(Self::Kafka),
            "WoodPecker" => Some(Self::WoodPecker),
            "Test" => Some(Self::Test),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum HighlightType {
    Lexical = 0,
    Semantic = 1,
}
impl HighlightType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Lexical => "Lexical",
            Self::Semantic => "Semantic",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Lexical" => Some(Self::Lexical),
            "Semantic" => Some(Self::Semantic),
            _ => None,
        }
    }
}
